workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == "main"

python-analyzer:
  rules:
    - changes:
        - python-analyzer/**/*
        - Jenkinsfile-python
  trigger:
    include: Jenkinsfile-python
