FROM python:3.9-slim
WORKDIR /python-analyzer 
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# 모델 파일용 디렉토리 생성 및 권한 설정
RUN mkdir -p /python-analyzer/models/saved/emotion_model && \
    chmod -R 755 /python-analyzer/models

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ..
EXPOSE 5001
CMD ["python", "api/app.py"]