FROM python:3.9-slim
WORKDIR /python-analyzer 
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# requirements.txt만 먼저 복사하여 캐싱 활용
COPY requirements.txt .
RUN pip install -r requirements.txt

# 나머지 파일들은 나중에 복사
COPY . .
EXPOSE 5001
CMD ["python", "api/app.py"]